
import React, { useState, useMemo } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { useAuthStore } from '@/store/authStore';
import { useLanguageStore } from '@/store/languageStore';
import { usePharmacyStore, Medicine } from '@/store/pharmacyStore';
import { ArrowRight, Plus, Search, AlertCircle, CheckCircle, FileText, RotateCcw } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import jsPDF from 'jspdf';

interface ShortageManagerProps {
  onBack: () => void;
}

const ShortageManager: React.FC<ShortageManagerProps> = ({ onBack }) => {
  const [medicineName, setMedicineName] = useState('');
  const [searchTerm, setSearchTerm] = useState('');
  const [showSuggestions, setShowSuggestions] = useState(false);
  
  const { user, checkPermission } = useAuthStore();
  const { language, t } = useLanguageStore();
  const { medicines, addMedicine, updateMedicine, deleteMedicine, getMedicineSuggestions } = usePharmacyStore();
  const { toast } = useToast();

  const suggestions = getMedicineSuggestions(medicineName);

  const filteredMedicines = useMemo(() => {
    return medicines.filter(medicine =>
      medicine.name.toLowerCase().includes(searchTerm.toLowerCase())
    );
  }, [medicines, searchTerm]);

  const shortages = filteredMedicines.filter(m => m.status === 'shortage');
  const available = filteredMedicines.filter(m => m.status === 'available');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!medicineName.trim()) {
      toast({
        title: language === 'ar' ? "خطأ" : "Error",
        description: language === 'ar' ? "يرجى إدخال اسم الدواء" : "Please enter medicine name",
        variant: "destructive",
      });
      return;
    }

    addMedicine({
      name: medicineName,
      status: 'shortage',
      lastUpdated: new Date().toISOString(),
      updatedBy: user?.name || ''
    });
    
    toast({
      title: language === 'ar' ? "تم الإضافة" : "Added",
      description: language === 'ar' ? `تم إضافة ${medicineName} كدواء ناقص` : `${medicineName} added as shortage`,
    });

    setMedicineName('');
    setShowSuggestions(false);
  };

  const toggleStatus = (medicine: Medicine) => {
    const newStatus = medicine.status === 'shortage' ? 'available' : 'shortage';
    updateMedicine(medicine.id, {
      status: newStatus,
      lastUpdated: new Date().toISOString(),
      updatedBy: user?.name || ''
    });
    
    toast({
      title: language === 'ar' ? "تم التحديث" : "Updated",
      description: language === 'ar' 
        ? `تم تحديث حالة ${medicine.name} إلى ${newStatus === 'available' ? 'متوفر' : 'ناقص'}`
        : `${medicine.name} status updated to ${newStatus}`,
    });
  };

  const exportShortagesPDF = () => {
    try {
      const doc = new jsPDF();
      
      // Header
      doc.setFontSize(16);
      doc.text('Al-Tiryak Al-Shafi Pharmacy', 20, 20);
      doc.text('Medicine Shortages Report', 20, 30);
      
      doc.setFontSize(12);
      doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 20, 45);
      doc.text(`Generated by: ${user?.name}`, 20, 55);
      
      // Table headers
      let yPosition = 75;
      doc.setFontSize(14);
      doc.text('No', 20, yPosition);
      doc.text('Drug Name', 50, yPosition);
      doc.text('Quantity', 150, yPosition);
      
      yPosition += 15;
      
      // Table content
      doc.setFontSize(11);
      shortages.forEach((medicine, index) => {
        doc.text((index + 1).toString(), 20, yPosition);
        doc.text(medicine.name, 50, yPosition);
        doc.text('_______', 150, yPosition);
        
        if (medicine.repeatCount && medicine.repeatCount > 1) {
          doc.text(`(Repeated: ${medicine.repeatCount}x)`, 50, yPosition + 10);
          yPosition += 5;
        }
        
        yPosition += 15;
        
        if (yPosition > 270) {
          doc.addPage();
          yPosition = 20;
        }
      });
      
      doc.save(`shortages-report-${new Date().toISOString().split('T')[0]}.pdf`);
      
      toast({
        title: language === 'ar' ? "تم التصدير" : "Exported",
        description: language === 'ar' ? "تم تصدير تقرير النواقص بنجاح" : "Shortages report exported successfully",
      });
    } catch (error) {
      toast({
        title: language === 'ar' ? "خطأ في التصدير" : "Export Error",
        description: language === 'ar' ? "حدث خطأ أثناء تصدير التقرير" : "Error occurred while exporting report",
        variant: "destructive",
      });
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-emerald-50 to-teal-100 relative">
      {/* Background Logo */}
      <div 
        className="absolute inset-0 flex items-center justify-center opacity-5 pointer-events-none"
        style={{
          backgroundImage: 'url(/lovable-uploads/e077b2e2-5bf4-4f3c-b603-29c91f59991e.png)',
          backgroundSize: '600px 600px',
          backgroundPosition: 'center',
          backgroundRepeat: 'no-repeat'
        }}
      />

      {/* Header */}
      <header className="bg-white shadow-sm border-b relative z-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-14">
            <div className="flex items-center">
              <Button
                onClick={onBack}
                variant="ghost"
                size="sm"
                className="flex items-center space-x-2 space-x-reverse text-sm"
              >
                <ArrowRight className="w-3 h-3" />
                <span>{t('back')}</span>
              </Button>
              <h1 className="text-lg font-bold text-gray-900 mr-4">{t('shortages.title')}</h1>
            </div>
            
            <Button onClick={exportShortagesPDF} size="sm" className="pharmacy-gradient text-sm px-3 py-1">
              <FileText className="w-3 h-3 ml-1" />
              {t('shortages.exportPdf')}
            </Button>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 relative z-10">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          
          {/* Add Medicine Form */}
          <div className="lg:col-span-1">
            <Card className="card-shadow">
              <CardHeader>
                <CardTitle className="text-lg">
                  {t('shortages.addShortage')}
                </CardTitle>
              </CardHeader>
              <CardContent>
                <form onSubmit={handleSubmit} className="space-y-4">
                  <div className="relative">
                    <label className="text-sm font-medium text-gray-700 mb-2 block">
                      {t('shortages.medicineName')}
                    </label>
                    <Input
                      value={medicineName}
                      onChange={(e) => {
                        setMedicineName(e.target.value);
                        setShowSuggestions(e.target.value.length >= 2);
                      }}
                      onFocus={() => setShowSuggestions(medicineName.length >= 2)}
                      onBlur={() => setTimeout(() => setShowSuggestions(false), 200)}
                      placeholder={language === 'ar' ? 'أدخل اسم الدواء' : 'Enter medicine name'}
                      className="text-right"
                    />
                    {showSuggestions && suggestions.length > 0 && (
                      <div className="absolute z-50 w-full mt-1 bg-white border border-gray-200 rounded-md shadow-lg">
                        {suggestions.map((suggestion, index) => (
                          <div
                            key={index}
                            className="px-3 py-2 hover:bg-gray-100 cursor-pointer text-right text-sm"
                            onClick={() => {
                              setMedicineName(suggestion);
                              setShowSuggestions(false);
                            }}
                          >
                            {suggestion}
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                  
                  <Button type="submit" className="w-full pharmacy-gradient">
                    <Plus className="w-4 h-4 ml-2" />
                    {t('shortages.addMedicine')}
                  </Button>
                </form>
              </CardContent>
            </Card>
          </div>

          {/* Medicine Lists */}
          <div className="lg:col-span-2 space-y-6">
            {/* Search */}
            <div className="relative">
              <Search className="absolute right-3 top-3 h-4 w-4 text-gray-400" />
              <Input
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                placeholder={language === 'ar' ? 'البحث عن دواء...' : 'Search for medicine...'}
                className="pl-10"
              />
            </div>

            {/* Shortages List */}
            <Card className="card-shadow">
              <CardHeader>
                <CardTitle className="flex items-center space-x-2 space-x-reverse text-red-600 text-lg">
                  <AlertCircle className="w-5 h-5" />
                  <span>{t('dashboard.shortages')} ({shortages.length})</span>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {shortages.map((medicine) => (
                    <div key={medicine.id} className="p-3 rounded-lg border-2 border-red-200 bg-red-50">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center space-x-2 space-x-reverse">
                          <AlertCircle className="w-4 h-4 text-red-500" />
                          <div>
                            <div className="flex items-center space-x-2 space-x-reverse">
                              <h3 className="font-medium text-gray-900 text-sm">{medicine.name}</h3>
                              {medicine.repeatCount && medicine.repeatCount > 1 && (
                                <Badge variant="outline" className="flex items-center space-x-1 text-xs">
                                  <RotateCcw className="w-2 h-2" />
                                  <span>{medicine.repeatCount}x {t('shortages.repeated')}</span>
                                </Badge>
                              )}
                            </div>
                            <p className="text-xs text-gray-500">
                              {language === 'ar' ? 'آخر تحديث:' : 'Last updated:'} {new Date(medicine.lastUpdated).toLocaleDateString()} 
                              {language === 'ar' ? ' بواسطة ' : ' by '} {medicine.updatedBy}
                            </p>
                          </div>
                        </div>
                        
                        <div className="flex items-center">
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => toggleStatus(medicine)}
                            className="bg-green-50 hover:bg-green-100 text-xs px-2 py-1"
                          >
                            {t('shortages.provided')}
                          </Button>
                        </div>
                      </div>
                    </div>
                  ))}
                  {shortages.length === 0 && (
                    <p className="text-center text-gray-500 py-8 text-sm">
                      {language === 'ar' ? 'لا توجد أدوية ناقصة' : 'No medicines in shortage'}
                    </p>
                  )}
                </div>
              </CardContent>
            </Card>

            {/* Available List */}
            <Card className="card-shadow">
              <CardHeader>
                <CardTitle className="flex items-center space-x-2 space-x-reverse text-green-600 text-lg">
                  <CheckCircle className="w-5 h-5" />
                  <span>{t('dashboard.available')} ({available.length})</span>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {available.map((medicine) => (
                    <div key={medicine.id} className="p-3 rounded-lg border-2 border-green-200 bg-green-50">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center space-x-2 space-x-reverse">
                          <CheckCircle className="w-4 h-4 text-green-500" />
                          <div>
                            <h3 className="font-medium text-gray-900 text-sm">{medicine.name}</h3>
                            <p className="text-xs text-gray-500">
                              {language === 'ar' ? 'آخر تحديث:' : 'Last updated:'} {new Date(medicine.lastUpdated).toLocaleDateString()} 
                              {language === 'ar' ? ' بواسطة ' : ' by '} {medicine.updatedBy}
                            </p>
                          </div>
                        </div>
                        
                        <div className="flex items-center">
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => toggleStatus(medicine)}
                            className="bg-red-50 hover:bg-red-100 text-xs px-2 py-1"
                          >
                            {t('shortages.outOfStock')}
                          </Button>
                        </div>
                      </div>
                    </div>
                  ))}
                  {available.length === 0 && (
                    <p className="text-center text-gray-500 py-8 text-sm">
                      {language === 'ar' ? 'لا توجد أدوية متوفرة' : 'No available medicines'}
                    </p>
                  )}
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
      
      {/* Footer */}
      <div className="absolute bottom-4 left-1/2 transform -translate-x-1/2 text-center text-sm text-gray-600 relative z-10">
        <p>Ahmed A Alrjele</p>
        <p>Founder & CEO</p>
        <p>Al-tiryak Al-shafi Pharmacy</p>
      </div>
    </div>
  );
};

export default ShortageManager;
